-- 1 Создание таблицы со скидками
CREATE TABLE IF NOT EXISTS discounts(
    discount_id integer primary key generated by default as identity, -- для гибкости
    client_id integer,
	discount_fraction integer,
	FOREIGN KEY (client_id) REFERENCES clients(client_id)
);

-- Предоставление скидки самым частым клиентам
INSERT INTO public.discounts (client_id, discount_fraction)
SELECT client_id, 10 AS discount_fraction
FROM public.orders
GROUP BY client_id
ORDER BY COUNT(*) DESC
LIMIT 10;

-- Проверка
SELECT discount_id, client_id, discount_fraction
FROM public.discounts

-- 2 Повышение зарплаты трем самым результативным работникам на 10%

-- 3 Представление для директора: филиал, кол-во заказов за месяц, заработанная сумма, прибыль

-- 4 Рейтинг самых надежных и ненадежных автомобилей

-- 5 Автомобиль какого цвета меньше всего посещает автосервис
