SELECT name, phone, email, password
FROM public.carcar_service;

-- В качестве уникального идентификатора используем phone клиента

-- Заполняем пустые ячейки поля name
WITH DistinctName AS (
	SELECT phone, name
	FROM carcar_service
	WHERE phone IS NOT NULL
	AND name IS NOT NULL
	GROUP BY phone, name
)
UPDATE public.carcar_service AS cs
SET name = dn.name
FROM DistinctName AS dn
WHERE cs.phone = dn.phone;

-- Заполняем пустые ячейки поля email
WITH DistinctEmail AS (
	SELECT phone, email
	FROM carcar_service
	WHERE phone IS NOT NULL
	AND email IS NOT NULL
	GROUP BY phone, email
)
UPDATE public.carcar_service AS cs
SET email = de.email
FROM DistinctEmail AS de
WHERE cs.phone = de.phone;

-- Заполняем пустые ячейки поля password
WITH DistinctPassword AS (
	SELECT phone, password
	FROM carcar_service
	WHERE phone IS NOT NULL
	AND password IS NOT NULL
	GROUP BY phone, password
)
UPDATE public.carcar_service AS cs
SET password = dp.password
FROM DistinctPassword AS dp
WHERE cs.phone = dp.phone;

-- Заполняем пустые ячейки поля phone
WITH DistinctPhone AS (
	SELECT email, phone
	FROM carcar_service
	WHERE email IS NOT NULL
	AND phone IS NOT NULL
	GROUP BY email, phone
)
UPDATE public.carcar_service AS cs
SET phone = dp.phone
FROM DistinctPhone AS dp
WHERE cs.email = dp.email;

-- Создаем отдельную таблицу clients
CREATE TABLE IF NOT EXISTS public.clients(
	client_id integer primary key generated by default as identity, -- для гибкости
	first_name text,
	last_name text,
	phone text,
	email text,
	password text
);

-- Заполняем таблицу уникальными значениями
INSERT INTO public.clients (first_name, last_name, phone, email, password)
SELECT DISTINCT split_part(name, ' ', 1) AS first_name, split_part(name, ' ', 2) AS last_name, phone, email, password
FROM public.carcar_service
ORDER BY first_name, last_name, email, phone;

-- Проверка
SELECT client_id, first_name, last_name, phone, email, password
FROM public.clients;
